# Form implementation generated from reading ui file 'ui/matrix.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(1100, 750)
        form.setStyleSheet("/* =========================\n"
"   Global settings\n"
"   ========================= */\n"
"#form {\n"
"    background-color: #1a1d23;\n"
"    font-family: Segoe UI Semibold;\n"
"}\n"
"\n"
"/* =========================\n"
"   Frames\n"
"   ========================= */\n"
"QFrame {\n"
"    border-radius: 8px;\n"
"    border: none;\n"
"}\n"
"\n"
"#matrixFrame {\n"
"    margin: 20 15 0 15\n"
"}\n"
"\n"
"#btnsFrame {\n"
"    background-color: transparent;\n"
"    margin: 5 15 30 15;\n"
"}\n"
"\n"
"/* =========================\n"
"   Table settings\n"
"   ========================= */\n"
"QTableWidget {\n"
"    background-color: #ffffff;\n"
"    color: #24292e;\n"
"    border: none;\n"
"    selection-background-color: #d4e8ff;\n"
"    selection-color: #24292e;\n"
"    gridline-color: #d1d5da;\n"
"    font-size: 13pt;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #d1d5da;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #d4e8ff;\n"
"    color: #24292e;\n"
"    border: 1px solid #00989b;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: #d4e8ff;\n"
"    color: #24292e;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* Fix for the editor widget that appears on double-click */\n"
"QTableWidget QLineEdit {\n"
"    border: 2px solid #00989b;\n"
"    background-color: #ffffff;\n"
"    color: #24292e;\n"
"    padding: 2px;\n"
"    margin: -1px;\n"
"    font-size: 13pt;\n"
"    selection-background-color: #4a9eff;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #004b4c;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #00585a;\n"
"    color: #ffffff;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: 600;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"/* =========================\n"
"   Buttons\n"
"   ========================= */\n"
"QPushButton {\n"
"    background-color: #0366d6;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 12px 20px;\n"
"    margin: 5 10 0 10;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0256c5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #024ea4;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #6c757d;\n"
"    color: #adb5bd;\n"
"}\n"
"\n"
"#modifyBtn {\n"
"    background-color: #6c757d;\n"
"}\n"
"\n"
"#modifyBtn:hover {\n"
"    background-color: #5a6268;\n"
"}\n"
"\n"
"#modifyBtn:pressed {\n"
"    background-color: #545b62;\n"
"}\n"
"\n"
"/* =========================\n"
"   Scrollbar\n"
"   ========================= */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #d1d5da;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #959da5;\n"
"    border-radius: 5px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #6a737d;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.matrixFrame = QtWidgets.QFrame(parent=form)
        self.matrixFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.matrixFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.matrixFrame.setObjectName("matrixFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.matrixFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.matrixTable = QtWidgets.QTableWidget(parent=self.matrixFrame)
        self.matrixTable.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.matrixTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.matrixTable.setShowGrid(True)
        self.matrixTable.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.matrixTable.setWordWrap(True)
        self.matrixTable.setCornerButtonEnabled(False)
        self.matrixTable.setRowCount(2)
        self.matrixTable.setColumnCount(2)
        self.matrixTable.setObjectName("matrixTable")
        self.matrixTable.horizontalHeader().setCascadingSectionResizes(False)
        self.matrixTable.horizontalHeader().setDefaultSectionSize(150)
        self.matrixTable.horizontalHeader().setSortIndicatorShown(False)
        self.matrixTable.horizontalHeader().setStretchLastSection(True)
        self.matrixTable.verticalHeader().setDefaultSectionSize(100)
        self.matrixTable.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.matrixTable)
        self.verticalLayout_3.addWidget(self.matrixFrame)
        self.btnsFrame = QtWidgets.QFrame(parent=form)
        self.btnsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.btnsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.btnsFrame.setObjectName("btnsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btnsFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.resultsBtn = QtWidgets.QPushButton(parent=self.btnsFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icons/score.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.resultsBtn.setIcon(icon)
        self.resultsBtn.setObjectName("resultsBtn")
        self.horizontalLayout.addWidget(self.resultsBtn)
        self.modifyBtn = QtWidgets.QPushButton(parent=self.btnsFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\icons/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.modifyBtn.setIcon(icon1)
        self.modifyBtn.setObjectName("modifyBtn")
        self.horizontalLayout.addWidget(self.modifyBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.btnsFrame)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Weighted Decision Matrix"))
        self.resultsBtn.setText(_translate("form", " Show results"))
        self.modifyBtn.setText(_translate("form", " Modify matrix"))
