# Form implementation generated from reading ui file 'ui/matrix.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(675, 589)
        form.setStyleSheet("/* =========================\n"
"   Global settings\n"
"   ========================= */\n"
"#form {\n"
"    background-color: #3A4446;\n"
"    font-family: Segoe UI Semibold;\n"
"}\n"
"\n"
"/* =========================\n"
"   Frames\n"
"   ========================= */\n"
"QFrame {\n"
"    border-radius: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"#titleFrame,\n"
"#matrixFrame,\n"
"#btnsFrame {\n"
"    margin: 0 20 0 20;\n"
"}\n"
"\n"
"#titleFrame {\n"
"    background-color: #4C5A5D;\n"
"    padding: 8px;\n"
"    margin-top: 20;\n"
"    margin-bottom: 10\n"
"}\n"
"\n"
"#matrixFrame {\n"
"    background-color: #5E6E71;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"#btnsFrame {\n"
"    background-color: transparent;\n"
"    margin-top: 10;\n"
"    margin-bottom: 10\n"
"}\n"
"\n"
"/* =========================\n"
"   Title\n"
"   ========================= */\n"
"#matrixTitle {\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    color: #F2F1ED;\n"
"}\n"
"\n"
"/* =========================\n"
"   Table settings\n"
"   ========================= */\n"
"QTableWidget {\n"
"    background-color: #FAFAF7;\n"
"    color: #2A3133;\n"
"    border: none;\n"
"    selection-background-color: #eef2f3;\n"
"    selection-color: #ffffff;\n"
"    gridline-color: #E0E0E0;\n"
"    font-size: 14pt;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 1px solid #E0E0E0;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #eef2f3;\n"
"    color: #2A3133;\n"
"    border: 1px solid #4e8fa6;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: #eef2f3;\n"
"    color: #2A3133;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* Fix for the editor widget that appears on double-click */\n"
"QTableWidget QLineEdit {\n"
"    border: 2px solid #3c7285;\n"
"    background-color: #eef2f3;\n"
"    color: #2A3133;\n"
"    padding: 2px;\n"
"    margin: -1px;\n"
"    font-size: 14pt;\n"
"    selection-background-color: #7dd3c0;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #4C5A5D;\n"
"    border: none\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #4C5A5D;\n"
"    color: #F2F1ED;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: 600\n"
"}\n"
"\n"
"/* =========================\n"
"   Buttons\n"
"   ========================= */\n"
"QPushButton {\n"
"    background-color: #57a695;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 14px;\n"
"    margin: 5 10 0 10;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6dbfad;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3f8878;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #83b1a7;\n"
"    color: #b8d5cf;\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleFrame = QtWidgets.QFrame(parent=form)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.matrixTitle = QtWidgets.QLabel(parent=self.titleFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.matrixTitle.setFont(font)
        self.matrixTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.matrixTitle.setObjectName("matrixTitle")
        self.verticalLayout_2.addWidget(self.matrixTitle)
        self.verticalLayout_3.addWidget(self.titleFrame)
        self.matrixFrame = QtWidgets.QFrame(parent=form)
        self.matrixFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.matrixFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.matrixFrame.setObjectName("matrixFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.matrixFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.matrixTable = QtWidgets.QTableWidget(parent=self.matrixFrame)
        self.matrixTable.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.matrixTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.matrixTable.setShowGrid(True)
        self.matrixTable.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.matrixTable.setWordWrap(True)
        self.matrixTable.setCornerButtonEnabled(False)
        self.matrixTable.setRowCount(2)
        self.matrixTable.setColumnCount(2)
        self.matrixTable.setObjectName("matrixTable")
        self.matrixTable.horizontalHeader().setCascadingSectionResizes(False)
        self.matrixTable.horizontalHeader().setDefaultSectionSize(150)
        self.matrixTable.horizontalHeader().setSortIndicatorShown(False)
        self.matrixTable.horizontalHeader().setStretchLastSection(True)
        self.matrixTable.verticalHeader().setDefaultSectionSize(100)
        self.matrixTable.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.matrixTable)
        self.verticalLayout_3.addWidget(self.matrixFrame)
        self.btnsFrame = QtWidgets.QFrame(parent=form)
        self.btnsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.btnsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.btnsFrame.setObjectName("btnsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btnsFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.resultsBtn = QtWidgets.QPushButton(parent=self.btnsFrame)
        self.resultsBtn.setObjectName("resultsBtn")
        self.horizontalLayout.addWidget(self.resultsBtn)
        self.modifyBtn = QtWidgets.QPushButton(parent=self.btnsFrame)
        self.modifyBtn.setObjectName("modifyBtn")
        self.horizontalLayout.addWidget(self.modifyBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.btnsFrame)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Interactive matrix"))
        self.matrixTitle.setText(_translate("form", "Weighted Decision Matrix"))
        self.resultsBtn.setText(_translate("form", "Show results"))
        self.modifyBtn.setText(_translate("form", "Modify matrix"))
