# Form implementation generated from reading ui file 'ui/rows.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(1100, 750)
        form.setStyleSheet("/* =========================\n"
"   Global settings\n"
"   ========================= */\n"
"#form {\n"
"    background-color: #1a1d23;\n"
"    font-family: Segoe UI;\n"
"}\n"
"\n"
"/* Selection colors */\n"
"QLineEdit {\n"
"    selection-background-color: #4a9eff;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"/* =========================\n"
"   Frames\n"
"   ========================= */\n"
"QFrame {\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#titleFrame {\n"
"    background: #00989b;\n"
"    padding: 20px;\n"
"    margin: 25px 25px 15px 25px;\n"
"    border: none;\n"
"}\n"
"\n"
"#contentFrame {\n"
"    background-color: #f5f7fa;\n"
"    padding: 20px;\n"
"    margin: 0px 25px 15px 25px;\n"
"    border: 1px solid #e1e4e8;\n"
"}\n"
"\n"
"#buttonsFrame {\n"
"    background-color: transparent;\n"
"    margin: 0px 15px 25px 15px;\n"
"}\n"
"\n"
"/* =========================\n"
"   Title styling\n"
"   ========================= */\n"
"#titleLabel {\n"
"    font-size: 20pt;\n"
"    font-weight: 600;\n"
"    color: #ffffff;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"#instructionLabel {\n"
"    font-size: 11pt;\n"
"    font-weight: 400;\n"
"    color: #b8d4f1;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"/* =========================\n"
"   Scroll area\n"
"   ========================= */\n"
"QScrollArea {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #d1d5da;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #959da5;\n"
"    border-radius: 5px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #6a737d;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* =========================\n"
"   Item cards\n"
"   ========================= */\n"
"#itemsWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* =========================\n"
"   Buttons\n"
"   ========================= */\n"
"#addBtn {\n"
"    background-color: #28a745;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    min-width: 55px;\n"
"    min-height: 55px;\n"
"    max-width: 55px;\n"
"    max-height: 55px;\n"
"}\n"
"\n"
"#addBtn:hover {\n"
"    background-color: #34ce57;\n"
"}\n"
"\n"
"#addBtn:pressed {\n"
"    background-color: #1e7e34;\n"
"}\n"
"\n"
"#nextBtn {\n"
"    background-color: #0366d6;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 14px 28px;\n"
"    font-size: 13pt;\n"
"    font-weight: 600;\n"
"    min-width: 130px;\n"
"}\n"
"\n"
"#nextBtn:hover {\n"
"    background-color: #0256c5;\n"
"}\n"
"\n"
"#nextBtn:pressed {\n"
"    background-color: #024ea4;\n"
"}\n"
"\n"
"#nextBtn:disabled {\n"
"    background-color: #6c757d;\n"
"    color: #adb5bd;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleFrame = QtWidgets.QFrame(parent=form)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(parent=self.titleFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.instructionLabel = QtWidgets.QLabel(parent=self.titleFrame)
        self.instructionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout_2.addWidget(self.instructionLabel)
        self.verticalLayout.addWidget(self.titleFrame)
        self.contentFrame = QtWidgets.QFrame(parent=form)
        self.contentFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contentFrame.setObjectName("contentFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contentFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.contentFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.itemsWidget = QtWidgets.QWidget()
        self.itemsWidget.setGeometry(QtCore.QRect(0, 0, 664, 224))
        self.itemsWidget.setObjectName("itemsWidget")
        self.itemsLayout = QtWidgets.QVBoxLayout(self.itemsWidget)
        self.itemsLayout.setSpacing(10)
        self.itemsLayout.setObjectName("itemsLayout")
        self.scrollArea.setWidget(self.itemsWidget)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.contentFrame)
        self.buttonsFrame = QtWidgets.QFrame(parent=form)
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.addBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icons/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addBtn.setIcon(icon)
        self.addBtn.setIconSize(QtCore.QSize(30, 30))
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nextBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout.addWidget(self.nextBtn)
        self.verticalLayout.addWidget(self.buttonsFrame)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Weighted Decision Matrix"))
        self.titleLabel.setText(_translate("form", "Add rows"))
        self.instructionLabel.setText(_translate("form", "Add the items you want to compare (minimum 2, maximum 8)"))
        self.nextBtn.setText(_translate("form", "Next"))
