# Form implementation generated from reading ui file 'ui/rows.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(800, 600)
        form.setStyleSheet("/* =========================\n"
"   Global settings\n"
"   ========================= */\n"
"#form {\n"
"    background-color: #3A4446;\n"
"    font-family: Segoe UI;\n"
"}\n"
"\n"
"/* =========================\n"
"   Frames\n"
"   ========================= */\n"
"QFrame {\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#titleFrame {\n"
"    background-color: #4C5A5D;\n"
"    padding: 15px;\n"
"    margin: 20px 20px 10px 20px;\n"
"}\n"
"\n"
"#contentFrame {\n"
"    background-color: #5E6E71;\n"
"    padding: 15px;\n"
"    margin: 0px 20px 10px 20px;\n"
"}\n"
"\n"
"#buttonsFrame {\n"
"    background-color: transparent;\n"
"    margin: 10px 20px 20px 20px;\n"
"}\n"
"\n"
"/* =========================\n"
"   Title styling\n"
"   ========================= */\n"
"#titleLabel {\n"
"    font-size: 18pt;\n"
"    font-weight: 600;\n"
"    color: #F2F1ED;\n"
"}\n"
"\n"
"#instructionLabel {\n"
"    font-size: 12pt;\n"
"    font-weight: 400;\n"
"    color: #B8C5C8;\n"
"}\n"
"\n"
"/* =========================\n"
"   Scroll area\n"
"   ========================= */\n"
"QScrollArea {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #4C5A5D;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #6B7B7E;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #7B8B8E;\n"
"}\n"
"\n"
"/* =========================\n"
"   Item cards\n"
"   ========================= */\n"
"#itemsWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* =========================\n"
"   Buttons\n"
"   ========================= */\n"
"#addBtn {\n"
"    background-color: #2fb14d;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    min-width: 50px;\n"
"    min-height: 50px;\n"
"    max-width: 50px;\n"
"    max-height: 50px;\n"
"}\n"
"\n"
"#addBtn:hover {\n"
"    background-color: #2ee154;\n"
"}\n"
"\n"
"#addBtn:pressed {\n"
"    background-color: #24943e;\n"
"}\n"
"\n"
"#nextBtn {\n"
"    background-color: #57a695;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 12px 24px;\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"#nextBtn:hover {\n"
"    background-color: #6dbfad;\n"
"}\n"
"\n"
"#nextBtn:pressed {\n"
"    background-color: #3f8878;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleFrame = QtWidgets.QFrame(parent=form)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(parent=self.titleFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.instructionLabel = QtWidgets.QLabel(parent=self.titleFrame)
        self.instructionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout_2.addWidget(self.instructionLabel)
        self.verticalLayout.addWidget(self.titleFrame)
        self.contentFrame = QtWidgets.QFrame(parent=form)
        self.contentFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contentFrame.setObjectName("contentFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contentFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.contentFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.itemsWidget = QtWidgets.QWidget()
        self.itemsWidget.setGeometry(QtCore.QRect(0, 0, 686, 241))
        self.itemsWidget.setObjectName("itemsWidget")
        self.itemsLayout = QtWidgets.QVBoxLayout(self.itemsWidget)
        self.itemsLayout.setSpacing(10)
        self.itemsLayout.setObjectName("itemsLayout")
        self.scrollArea.setWidget(self.itemsWidget)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.contentFrame)
        self.buttonsFrame = QtWidgets.QFrame(parent=form)
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.addBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icons/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addBtn.setIcon(icon)
        self.addBtn.setIconSize(QtCore.QSize(30, 30))
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nextBtn = QtWidgets.QPushButton(parent=self.buttonsFrame)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout.addWidget(self.nextBtn)
        self.verticalLayout.addWidget(self.buttonsFrame)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Add rows"))
        self.titleLabel.setText(_translate("form", "Add rows"))
        self.instructionLabel.setText(_translate("form", "Add the items you want to compare (minimum 2, maximum 8)"))
        self.nextBtn.setText(_translate("form", "Next"))
